#! /bin/sh
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="Phantomjs service"
NAME=phantomjs
DAEMON=/usr/bin/\$NAME
PIDFILE=/var/run/\$NAME.pid
SCRIPTNAME=/etc/init.d/\$NAME
[ -x "\$DAEMON" ] || exit 0
. /lib/init/vars.sh
. /lib/lsb/init-functions
WEBDRIVER_PORT=8190
DEBUG=false
LOG_FILE=/var/log/phantomjs.log
[ -r /etc/default/\$NAME ] && . /etc/default/\$NAME
DAEMON_ARGS="--webdriver=\$WEBDRIVER_PORT --debug=\$DEBUG"
do_start()
{
 start-stop-daemon --start --quiet --pidfile \$PIDFILE --exec \$DAEMON --test > /dev/null
 || return 1
start-stop-daemon --start --background --quiet --pidfile \$PIDFILE --exec /bin/bash -- -c "\$DAEMON \$DAEMON_ARGS > \$LOG_FILE 2>&1"
 || return 2
}
do_stop()
{
 start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile \$PIDFILE --name \$NAME
 RETVAL="\$?"
 [ "\$RETVAL" = 2 ] && return 2
 start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec \$DAEMON \
 [ "\$?" = 2 ] && return 2
 rm -f \$PIDFILE
 return "\$RETVAL"
}
do_reload() {
 start-stop-daemon --stop --signal 1 --quiet --pidfile \$PIDFILE --name \$NAME
 return 0
}

case "\$1" in
 start)
 [ "\$VERBOSE" != no ] && log_daemon_msg "Starting \$DESC" "\$NAME"
 do_start
 case "\$?" in
 0|1) [ "\$VERBOSE" != no ] && log_end_msg 0 ;;
 2) [ "\$VERBOSE" != no ] && log_end_msg 1 ;;
 esac
 ;;
 stop)
 [ "\$VERBOSE" != no ] && log_daemon_msg "Stopping \$DESC" "\$NAME"
 do_stop
 case "\$?" in
 0|1) [ "\$VERBOSE" != no ] && log_end_msg 0 ;;
 2) [ "\$VERBOSE" != no ] && log_end_msg 1 ;;
 esac
 ;;
 status)
 status_of_proc "\$DAEMON" "\$NAME" && exit 0 || exit \$?
 ;;
 restart|force-reload)
 log_daemon_msg "Restarting \$DESC" "\$NAME"
 do_stop
 case "\$?" in
 0|1)
 do_start
 case "\$?" in
 0) log_end_msg 0 ;;
 1) log_end_msg 1 ;;
 *) log_end_msg 1 ;;
 esac
 ;;
 *)
 log_end_msg 1
 ;;
 esac
 ;;
 *)
 echo "Usage: \$SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
 exit 3
 ;;
esac
